# Generated by Django 3.2.9 on 2021-11-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
            ],
        ),
    ]
